[package]
name = "kb"
version = "1.1.0"
authors = ["Sagittarius-a <humnoplease@no.pe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
anyhow = "1.0"
